### ISSUE TITLE
Create output files according to ymeteor

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ts4cpp#1]
The output files we need according to [ymeteor](https://github.com/zdavatz/ymeteor) are:

1. chargenrueckrufe_de.json
2. dhpc_hpc_de.json
3. chargenrueckrufe_fr.json
4. dhpc_hpc_fr.json
5. drugshortage.json

**Comment by b123400** [comment]
TODO list

- [x] chargenrueckrufe_de.json
- [x] dhpc_hpc_de.json
- [x] chargenrueckrufe_fr.json
- [x] dhpc_hpc_fr.json
- [x] drugshortage.json
