### ISSUE TITLE
DHPC/HPC without Zulassungsnummer

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ts4cpp#3]
For the *76* DHPC/HPC News items that do not contain a registration number we need a mapping table. One possibility would be that we do a look-up for the Registration number via the name after the long "—" for example:

1. [DHPC – Xeljanz (tofacitinib)](https://www.swissmedic.ch/swissmedic/de/home/humanarzneimittel/marktueberwachung/health-professional-communication--hpc-/dhpc-xeljanz-tofacitinib.html) the product name is "Xeljanz" and the active agent is "tofacitinib".
2. [HPC – Brivex (Brivudin)](https://www.swissmedic.ch/swissmedic/de/home/humanarzneimittel/marktueberwachung/health-professional-communication--hpc-/hpc-brivex-brivudin.html) the product name is "Brivex" and the active agent is "Brivudin".
3. You do the lookup in the file [zugelassene_packungen_ham.xlsx](https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx) and add the information to the JSON file, so the News item can be mappend in the sqlite HTML.
4. For the ones that are really difficult to map, we just do a manual mapping via a File that we commit via git on regular basis.

**Comment by zdavatz** [comment]
related to: https://github.com/zdavatz/cpp2sqlite/issues/178

**Comment by b123400** [comment]
This should be fixed in https://github.com/zdavatz/ts4cpp/commit/51957bcc22c3149cb52c7c00b530e632b89b7e75

**Comment by b123400** [comment]
This should be ready now. You have to put `zugelassene_packungen_ham.xlsx` in `input/`

**Comment by zdavatz** [comment]
Ok, lets include a download function as well. I will open an issue.
